name: MDReader
options:
  bundleIdPrefix: com.san
  deploymentTarget:
    iOS: "26.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "3KBA253B3F"
    CODE_SIGN_STYLE: Automatic
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: YES

targets:
  MDReader:
    type: application
    platform: iOS
    sources:
      - path: MDReader
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.san.mdreader
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: MDReader/Info.plist
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
